version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: etl-mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: etl_pipeline
    volumes:
      - mongodb_data:/data/db
    command: ["--replSet", "rs0", "--bind_ip_all"]
    networks:
      - etl-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: etl-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - etl-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: etl-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - etl-network

  postgres:
    image: postgres:16
    container_name: etl-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: warehouse
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - etl-network

volumes:
  mongodb_data:
  postgres_data:

networks:
  etl-network:
    driver: bridge